env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
